import { BORDER_RADIUS_PIXELS, CONTROLS } from "../common-init";

export const initialState = {
  sequenceNumber: null,
  id: "",
  draftAreaId: "",
  specialPage: [],
  areaName: "",
  areaType: CONTROLS.TITLE,
  show: true,
  model: "",
  title: {
    name: "",
    content: "",
    properties: {
      color: "#000000",
      fontFamily: "sans-serif",
      wordBreak: "normal",
      fontSize: "2rem",
      fontWeight: "",
      gridProps: {
        gridColumn: "1 / 6",
        gridRow: "",
      },
      margin: "0",
      padding: "0",
      textAlign: "start",
    },
  },
  subTitle: {
    name: "",
    content: "",
    properties: {
      color: "#000000",
      fontFamily: "sans-serif",
      wordBreak: "normal",
      fontSize: "1rem",
      fontWeight: "",
      gridProps: {
        gridColumn: "1 / 6",
        gridRow: "",
      },
      margin: "0",
      padding: "0",
      textAlign: "start",
    },
  },
  content: {
    name: "",
    content: "",
    properties: {
      color: "#000000",
      fontFamily: "sans-serif",
      wordBreak: "normal",
      fontSize: "1rem",
      fontWeight: "",
      gridProps: {
        gridColumn: "1 / 6",
        gridRow: "",
      },
      margin: "0",
      padding: "0",
      textAlign: "start",
    },
  },
  imagesPerLine: 2,
  numberOfLines: 1,
  carousel: false,
  properties: {
    backgroundColor: "#ffffff",
    textAlignment: "Left",
    heightLabel: "M",
    heightPercentage: 0.5,
    margin: "",
    padding: "",
    borderTopLeftRadius: `0${BORDER_RADIUS_PIXELS}`,
    borderTopRightRadius: `0${BORDER_RADIUS_PIXELS}`,
    borderBottomLeftRadius: `0${BORDER_RADIUS_PIXELS}`,
    borderBottomRightRadius: `0${BORDER_RADIUS_PIXELS}`,
    display: "grid",
    gridProps: {
      gridTemplateColumns: "repeat(2, 1fr)",
      gridTemplateRows: "",
      rowGap: "0px",
      columnGap: "0px",
      gridAutoRows: "minmax(auto, auto)",
      gridAutoFlow: "row",
    },
    flexProps: {
      flexDirection: "column",
      flexWrap: "",
      flexFlow: "",
    },
    scrollable: false,
    scrollProps: {
      overflowX: "unset",
      overflowY: "unset",
      scrollBehavior: "smooth",
    },
    border: "1px solid #fff",
    width: "100%",
    height: "100vh",
    justifyContent: "flex-start",
    alignItems: "center",

    url: "",
    backgroundImage: false,
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundAttachment: "scroll",
    backgroundPosition: "center",
    backgroundOpacity: "linear-gradient(#ffffff, #ffffff)",
    backgroundOpacityValue: "0",
  },
}